conf:
  base_url : "http://192.168.101.89:18081"
  target : "人行CNCC云管平台"
  description : "Git版本：,日期： ,版本描述："
  test_suite : "TestCase1"
  excel : "Pbank-portal_wzy.xlsx"
  variable : 'variable.yaml'
  case_level: 'P1'

mysql :
  host : '192.168.101.89'
  port : 13307
  username : 'root'
  password : 'h3croot'
  db_name : 'pbank-portal'
  charset : 'utf-8'
